services:
  - type: web
    name: lms-pro
    runtime: docker
    repo: https://github.com/LeudjeuNjiatcha-YanisAel/LMS---Pro
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: lms-pro-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: lms-pro-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: lms-pro-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: lms-pro-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: lms-pro-db
          property: port

databases:
  - name: lms-pro-db
    databaseName: lms_db
    plan: free
